import "./globals.css";
import { Raleway } from "next/font/google";
import { CartProvider } from "@/components/context/CartContext";

//Componentes
import NavBar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { AuthProvider } from "@/components/context/AuthContext";

//metadata renombra el titulo de cada page
export const metadata = {
  title: "Welcome! , Happy buying",
  description: "Generated by Next.js",
};

const roboto = Raleway({
  weight: ["400", "700"],
  style: ["italic", "normal"],
  subsets: ["latin"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <AuthProvider>
          <CartProvider>
            <NavBar />
            {children}
            <Footer />
          </CartProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
